In [1]:
import numpy as np
np.dot(3,4)

12

In [2]:
np.dot([2j,3j],[2j,3j])


(-13+0j)

In [3]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.dot(a,b)


array([[4, 1],
       [2, 2]])

In [6]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a,b)[2,3,2,1,2,2]

499128

In [7]:
sum(a[2,3,2,:]* b[1,2,:,2])

499128

In [11]:
from numpy.linalg import multi_dot
A = np.random.random((10000,100))
B = np.random.random((100,1000))
C = np.random.random((1000,5))
D = np.random.random((5,333))

_ = multi_dot([A, B, C, D])

In [12]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a,b)


(70-8j)

In [13]:
np.vdot(b,a)

(70+8j)

In [14]:
a = np.array([[1,4],[5,6]])
b = np.array([[4,1],[2,2]])
np.vdot(a,b)

30

In [15]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a,b)

2

In [18]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
c = np.inner(a,b)
c.shape

(2, 3)

In [19]:
np.inner(np.eye(2),7)

array([[7., 0.],
       [0., 7.]])

In [20]:
rl =  np.outer(np.ones((5,)),np.linspace(-2,3,5))
rl

array([[-2.  , -0.75,  0.5 ,  1.75,  3.  ],
       [-2.  , -0.75,  0.5 ,  1.75,  3.  ],
       [-2.  , -0.75,  0.5 ,  1.75,  3.  ],
       [-2.  , -0.75,  0.5 ,  1.75,  3.  ],
       [-2.  , -0.75,  0.5 ,  1.75,  3.  ]])

In [22]:
im = np.outer(1j*np.linspace(2,-2,5),np.ones((5,)))

In [23]:
im


array([[0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j],
       [0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j]])

In [24]:
grid = rl+im
grid

array([[-2.  +2.j, -0.75+2.j,  0.5 +2.j,  1.75+2.j,  3.  +2.j],
       [-2.  +1.j, -0.75+1.j,  0.5 +1.j,  1.75+1.j,  3.  +1.j],
       [-2.  +0.j, -0.75+0.j,  0.5 +0.j,  1.75+0.j,  3.  +0.j],
       [-2.  -1.j, -0.75-1.j,  0.5 -1.j,  1.75-1.j,  3.  -1.j],
       [-2.  -2.j, -0.75-2.j,  0.5 -2.j,  1.75-2.j,  3.  -2.j]])

In [25]:
x = np.array(['a','b','c'],dtype=object)
np.outer(x,[1,2,3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [26]:
a = np.ones([9,5,7,4])
c = np.ones([9,5,4,3])
np.dot(a,c).shape

(9, 5, 7, 9, 5, 3)

In [27]:
np.matmul(a,c).shape

(9, 5, 7, 3)

In [28]:
a = np.array([[1,0],
              [0,1]])
b = np.array([[4,1],
             [2,2]])
np.matmul(a,b)


array([[4, 1],
       [2, 2]])

In [29]:
a = np.array([[1,0],
              [0,1]])
b = np.array([1,2])
np.matmul(a,b)


array([1, 2])

In [30]:
np.matmul(b,a)

array([1, 2])

In [31]:
a = np.arange(2*2*4).reshape((2,2,4))
b = np.arange(2*2*4).reshape((2,4,2))
np.matmul(a,b).shape

(2, 2, 2)

In [32]:
np.matmul(a,b)[0,1,1]


98

In [35]:
sum(a[0,1,:]*b[0,:,1])

98

In [36]:
np.matmul([2j,3j],[2j,3j])

(-13+0j)

In [37]:
x1 = np.array([2j,3j])
x2 = np.array([2j,3j])
x1 @ x2

(-13+0j)

In [38]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b,axes = ([1,0],[0,1]))
c.shape

(5, 2)

In [39]:
c

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [41]:
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
c == d

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [42]:
a = np.array(range(1,9))
a.shape = (2,2,2)
A = np.array(('a','b','c','d'), dtype=object)
A.shape = (2,2)
a; A

array([['a', 'b'],
       ['c', 'd']], dtype=object)

In [43]:
np.tensordot(a,A,1)

array([[['acc', 'bdd'],
        ['aaacccc', 'bbbdddd']],

       [['aaaaacccccc', 'bbbbbdddddd'],
        ['aaaaaaacccccccc', 'bbbbbbbdddddddd']]], dtype=object)

In [44]:
np.tensordot(a,A,0)

array([[[[['a', 'b'],
          ['c', 'd']],

         [['aa', 'bb'],
          ['cc', 'dd']]],


        [[['aaa', 'bbb'],
          ['ccc', 'ddd']],

         [['aaaa', 'bbbb'],
          ['cccc', 'dddd']]]],



       [[[['aaaaa', 'bbbbb'],
          ['ccccc', 'ddddd']],

         [['aaaaaa', 'bbbbbb'],
          ['cccccc', 'dddddd']]],


        [[['aaaaaaa', 'bbbbbbb'],
          ['ccccccc', 'ddddddd']],

         [['aaaaaaaa', 'bbbbbbbb'],
          ['cccccccc', 'dddddddd']]]]], dtype=object)

In [45]:
np.tensordot(a,A,(0,1))

array([[['abbbbb', 'cddddd'],
        ['aabbbbbb', 'ccdddddd']],

       [['aaabbbbbbb', 'cccddddddd'],
        ['aaaabbbbbbbb', 'ccccdddddddd']]], dtype=object)

In [46]:
np.tensordot(a,A,(2,1))

array([[['abb', 'cdd'],
        ['aaabbbb', 'cccdddd']],

       [['aaaaabbbbbb', 'cccccdddddd'],
        ['aaaaaaabbbbbbbb', 'cccccccdddddddd']]], dtype=object)

In [48]:
np.tensordot(a, A,((0,1), (0,1)))

array(['abbbcccccddddddd', 'aabbbbccccccdddddddd'], dtype=object)

In [49]:
np.tensordot(a,A,((2,1),(1,0)))

array(['acccbbdddd', 'aaaaacccccccbbbbbbdddddddd'], dtype=object)

In [52]:
import numpy as np
from numpy import linalg as LA
x = np.random.random()
Q = np.array([[np.cos(x), -np.sin(x)],[np.sin(x),np.cos(x)]])
LA.norm(Q[0,:]),LA.norm(Q[1,:]),np.dot(Q[0,:],Q[1,:])

(1.0, 1.0, 0.0)

In [53]:
D = np.diag((-1,1))
LA.eigvals(D)


array([-1.,  1.])

In [54]:
A = np.dot(Q,D)
A = np.dot(A,Q.T)
LA.eigvals(A)

array([-1.,  1.])