In [7]:
import numpy as np

val_mul = np.array([(3, 4, 2, 5), (3, 6, 2, 4), (1, 5, 2, 6)])
slice_val = val_mul[:2, :2]
print(val_mul[1][1])


6


In [9]:
import numpy as np

val_mul = np.array([(3, 4, 2, 5), (3, 6, 2, 4), (1, 5, 2, 6)])
slice_val = val_mul[:2, :2]
print("First 2 rows and columns of the array\n", slice_val)

First 2 rows and columns of the array
 [[3 4]
 [3 6]]


In [12]:
val_mul1=np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6),(1,5,0,1),(7,3,3,0)])
slice_step_row = val_mul1[::2, :2]
print("All rows and 2 columns of the array with step size of 2 along the row\n", slice_step_row)

All rows and 2 columns of the array with step size of 2 along the row
 [[3 4]
 [1 5]
 [7 3]]


In [16]:
val_mul1=np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6),(1,5,0,1),(7,3,3,0)])

In [14]:
mul_idx_arr = val_mul1[
    [1,2,2,3],
    [1,2,3,3]
]
print("\nAccesing Elements at multiple indices (1,1),(2,2),(2,3),(3,3)-->", mul_idx_arr)


Accesing Elements at multiple indices (1,1),(2,2),(2,3),(3,3)--> [6 2 6 1]


In [17]:
condition = val_mul > 3
res = val_mul[condition]
print (res)

[4 5 6 4 5 6]


In [18]:
val1 = np.array([1,5,2,6])
print(val1.ndim)

1


In [22]:
val = np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6)])
print(val)

val = val.reshape(2,6)
print(val)

[[3 4 2 5]
 [3 6 2 4]
 [1 5 2 6]]
[[3 4 2 5 3 6]
 [2 4 1 5 2 6]]


In [23]:
print(val.T)

[[3 2]
 [4 4]
 [2 1]
 [5 5]
 [3 2]
 [6 6]]


In [24]:
val = np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6)])
print(val.ravel())

[3 4 2 5 3 6 2 4 1 5 2 6]


In [26]:
print (val.itemsize)

8


In [27]:
print (val.dtype)

int64


In [28]:
val = np.ones(3)
print(val)

val0=np.zeros(3)
print(val0)

[1. 1. 1.]
[0. 0. 0.]


In [32]:
val = np.linspace(2,5,8)
print(val)

[2.         2.42857143 2.85714286 3.28571429 3.71428571 4.14285714
 4.57142857 5.        ]


In [34]:
val = np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6)])
print(val.max())

6


In [35]:
print(val.min())

1


In [36]:
print(val.sum())

43


In [37]:
val = np.array([1,4,9])
print(np.sqrt(val))

[1. 2. 3.]


In [38]:
print(np.std(val))

3.2998316455372216


In [40]:
val = np.array([(3,4,2,5),(3,6,2,4),(1,5,2,6)])
print(val+3)

[[6 7 5 8]
 [6 9 5 7]
 [4 8 5 9]]


In [41]:
print(np.sort(val,axis=1))

[[2 3 4 5]
 [2 3 4 6]
 [1 2 5 6]]


In [42]:
print(np.sort(val,axis=0))

[[1 4 2 4]
 [3 5 2 5]
 [3 6 2 6]]


In [43]:
arr = np.array([8,94,8,56,7,3,2,1,0])
print(np.where(arr>10))

(array([1, 3]),)


In [46]:
np.savetxt('arr_file.csv',arr,delimiter=',')

In [48]:
np.loadtxt('arr_file.csv',delimiter=',')

array([ 8., 94.,  8., 56.,  7.,  3.,  2.,  1.,  0.])