In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:

x = np.array([5,15,25,35,45,55]).reshape((-1,1))
y = np.array([5,20,14,32,22,38])

In [3]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [4]:
y

array([ 5, 20, 14, 32, 22, 38])

In [5]:
model = LinearRegression()

In [6]:
model.fit(x,y)

LinearRegression()

In [7]:
model = LinearRegression().fit(x,y)

In [8]:
r_sq = model.score(x,y)

In [9]:
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.7158756137479542


In [10]:
print(f"intercept {model.intercept_}")

intercept 5.633333333333329


In [11]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [12]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))

In [13]:
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [14]:
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [15]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [16]:
x_new = np.arange(5).reshape((-1,1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [17]:
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [18]:
x = [[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]
y = [4,5,20,14,32,22,38,43]
x,y = np.array(x), np.array(y)

In [20]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [21]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [22]:
model = LinearRegression().fit(x,y)

In [24]:
r_sq = model.score(x,y)
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
coefficients: [0.44706965 0.25502548]


In [25]:
y_pred = model.predict(x)
print(f"predicted response: \n{y_pred}")

predicted response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [27]:
x_new =  np.arange(10).reshape((-1,2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
y_new = model.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

In [29]:


from sklearn.preprocessing import PolynomialFeatures

In [30]:
x = np.array([5,15,25,35,45,55]).reshape((-1,1))
y = np.array([15,11,2,8,25,32])


In [31]:
transformer = PolynomialFeatures(degree=2, include_bias=False)


In [32]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [33]:
x_ = transformer.transform(x)

In [34]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [35]:
x_


array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [36]:
model = LinearRegression().fit(x_,y)


In [38]:
r_sq = model.score(x_,y)

In [39]:
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498564
intercept: 21.37232142857144
coefficients: [-1.32357143  0.02839286]


In [40]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)
x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [41]:
model = LinearRegression(fit_intercept=False).fit(x_,y)


In [42]:
r_sq = model.score(x_,y)

In [45]:
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")
print(f"predicted response: \n{y_pred}")

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]
predicted response: 
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [44]:
y_pred = model.predict(x_)
print(f"predicted response: \n{y_pred}")

predicted response: 
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


AdvanceD Linear with Statsmodels



In [46]:
import numpy as np
import statsmodels.api as sm

In [47]:
x = [[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]
y = [4,5,20,14,32,22,38,43]
x,y = np.array(x), np.array(y)


In [48]:
x = sm.add_constant(x)

In [49]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [50]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [51]:
model = sm.OLS(y,x)


In [52]:
results = model.fit()

In [53]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Wed, 06 Mar 2024   Prob (F-statistic):            0.00713
Time:                        11:24:54   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [55]:
print(f"coefficient of determination: {results.rsquared}")
print(f"adjusted coefficient of determination: {results.rsquared_adj}")
print(f"regression coefficients: {results.params}")

coefficient of determination: 0.8615939258756776
adjusted coefficient of determination: 0.8062314962259487
regression coefficients: [5.52257928 0.44706965 0.25502548]


In [56]:
print(f"predicted response: \n{results.fittedvalues}")

predicted response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [57]:
print(f"predicted response: \n{results.predict(x)}")

predicted response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [58]:
x_new = sm.add_constant(np.arange(10).reshape((-1,2)))
x_new

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.],
       [1., 6., 7.],
       [1., 8., 9.]])

In [59]:
y_new = results.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])