In [8]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.random.randn(1,100)
hidden_layers = [50]*5
use_activation = ['tanh']*len(hidden_layers)
activation_dict = {'tanh' :lambda x:np.tanh(x),'sigmoid':lambda x:1/(1+np.exp(-x))}
H_mat = {}

{}


In [6]:
for i in range(len(hidden_layers)):
  if i==0:
    X = x
  else:
    X = H_mat[i-1]
  fan_in = X.shape[1]
  fan_out = hidden_layers[i]

  W = np.random.randn(fan_in,fan_out)*0.01
  H = np.dot(X,W)
  H = activation_dict[use_activation[i]](H)
  H_mat[i] = H
  print(H_mat[i])

[[ 0.09518513  0.0398733   0.10787771  0.0182427  -0.17637041  0.04343999
  -0.06760087 -0.04645221 -0.106766    0.01750541 -0.0706044  -0.17400803
  -0.20936424 -0.08542157  0.0286634  -0.29969438  0.06100458 -0.06073725
  -0.01741584  0.07265491 -0.05661208 -0.21961229  0.1060012   0.15808992
   0.04926945  0.06003499 -0.02019806  0.09943728  0.15135845  0.13066957
  -0.10387938 -0.06647543  0.08494016  0.04036981 -0.0106701  -0.02310335
   0.01630151  0.13130644 -0.21484021  0.03510534 -0.08752704 -0.02765387
   0.11018415 -0.16684375  0.11131802 -0.18198313  0.08224514 -0.02301869
  -0.0646525   0.03167448]]
[[ 0.0178112   0.00546349 -0.00356787  0.00134752  0.00069494 -0.01063383
  -0.00081056 -0.00422535 -0.0051908  -0.0045335  -0.00799354  0.00416273
   0.01569572  0.01090353  0.00098612  0.00214546 -0.00594777 -0.00656893
   0.00139972 -0.01565207 -0.00328306 -0.00044179  0.0056156   0.00152094
  -0.00259179 -0.00083524 -0.00288415 -0.01568915  0.00415623 -0.01199587
  -0.01105

In [7]:
W = np.random.rand(fan_in,fan_out)
print(W)

[[0.65987012 0.63463258 0.73804233 ... 0.33181751 0.22035185 0.04677523]
 [0.88141174 0.67521322 0.96268969 ... 0.32225978 0.71945667 0.60677649]
 [0.42175698 0.43049199 0.3696086  ... 0.52731503 0.0230205  0.78590461]
 ...
 [0.16353151 0.69303966 0.34521358 ... 0.16953686 0.05189874 0.41650257]
 [0.59574449 0.93236042 0.42419837 ... 0.81865794 0.79200168 0.1922714 ]
 [0.54358603 0.6167515  0.38861417 ... 0.22771998 0.06018748 0.25367068]]


In [9]:
from tensorflow.keras import layers
from tensorflow.keras import initializers

In [11]:
initializer = tf.keras.initializers.Zeros()
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(initializer)

In [12]:
initializer = tf.keras.initializers.RandomNormal(
    mean=0,stddev=1
)
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)

In [13]:
initializer = tf.keras.initializers.RandomUniform(
    minval = 0,maxval =1.
)
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)

In [14]:
initializer = tf.keras.initializers.GlorotUniform()
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)

In [15]:
initializer = tf.keras.initializers.GlorotNormal()
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)

In [16]:
initializer = tf.keras.initializers.HeUniform()
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)

In [17]:
initializer = tf.keras.initializers.HeNormal()
layer = tf.keras.layers.Dense(
    3,kernel_initializer=initializer)
print(layer)