In [2]:
import tensorflow as tf

print ("Tensorflow version:" , tf.__version__)


Tensorflow version: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train,x_test = x_train/ 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28 , 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions


array([[-0.02512112, -0.18291989, -0.3390941 ,  0.29860878,  0.4147936 ,
         0.12481426, -0.09382654,  0.4390348 ,  1.1891813 , -0.690597  ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.07640929, 0.06525519, 0.05581994, 0.10561857, 0.11863114,
        0.08876919, 0.07133584, 0.12154203, 0.2573422 , 0.03927657]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.4217157

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train,y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.3053 - accuracy: 0.9100
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1468 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1101 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0886 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0761 - accuracy: 0.9756


In [12]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0789 - accuracy: 0.9766 - 698ms/epoch - 2ms/step


[0.07888928800821304, 0.9765999913215637]

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])



In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.03517150e-08, 1.64913905e-09, 8.19486195e-06, 7.57554299e-05,
        1.36277266e-11, 4.20722614e-07, 9.30534810e-15, 9.99914646e-01,
        5.45156134e-08, 8.10090569e-07],
       [2.82963004e-08, 5.62805217e-04, 9.99302506e-01, 1.32522357e-04,
        2.29519442e-17, 2.03564309e-06, 2.77122396e-08, 3.17865681e-14,
        1.02600588e-07, 3.64351392e-14],
       [1.05186439e-06, 9.99236941e-01, 3.00518423e-05, 1.88598242e-05,
        1.73978970e-05, 2.37740392e-06, 1.17820136e-05, 4.70669242e-04,
        2.10041617e-04, 7.38264532e-07],
       [9.99921560e-01, 6.92910285e-10, 1.29834498e-05, 5.61994682e-07,
        2.43690188e-08, 1.17208028e-05, 9.05316210e-06, 7.09457299e-06,
        3.25222054e-08, 3.68992078e-05],
       [1.04734099e-05, 1.04904965e-08, 2.40901272e-06, 5.60249482e-08,
        9.95431900e-01, 4.99343059e-07, 3.83864281e-05, 1.56060269e-04,
        8.08922209e-07, 4.35946183e-03]], dtype=float32)>